### ISSUE TITLE
in memory option throws if memdown is not installed

### ISSUE THREAD

**Issue by robertkowalski** [pouchdb/pouchdb-server#122]
The in-memory option throws if memdown is not installed.

As I use the in memory option the expected behaviour would be that memdown is not required for it.

``` 
> the-database@1.0.0 start /home/rocko/sourcecode/database
> pouchdb-server --in-memory

module.js:339
    throw err;
    ^

Error: Cannot find module 'memdown'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at updatePouchDB (/home/rocko/sourcecode/database/node_modules/pouchdb-server/bin/pouchdb-server:211:15)
    at Object.<anonymous> (/home/rocko/sourcecode/database/node_modules/pouchdb-server/bin/pouchdb-server:225:1)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3

npm ERR! Linux 3.13.0-71-generic
npm ERR! argv "/home/rocko/.nvm/versions/node/v4.2.2/bin/node" "/home/rocko/.nvm/versions/node/v4.2.2/bin/npm" "start"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! the-database@1.0.0 start: `pouchdb-server --in-memory`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the the-database@1.0.0 start script 'pouchdb-server --in-memory'.
npm ERR! This is most likely a problem with the the-database package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     pouchdb-server --in-memory
npm ERR! You can get their info via:
npm ERR!     npm owner ls the-database
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/rocko/sourcecode/database/npm-debug.log
```
```

**Comment by robertkowalski** [comment]
looks like my npm is broken... :/
