### ISSUE TITLE
Replicate to self causes PouchDB to terminate

### ISSUE THREAD

**Issue by craigminihan** [pouchdb/pouchdb-server#129]
If you replicate a db to another db (different name) in a PouchDB instance the process terminates.

Restarting `pouchdb-server` results in the same error.

Things are sweet until:

``` text
[info] GET /_replicator 200 - 192.168.0.70
[info] GET / 200 - 192.168.0.70
[info] GET /_replicator/_all_docs?include_docs=true&limit=0 200 - 192.168.0.70
[info] GET /_session 200 - 192.168.0.70

/usr/local/lib/node_modules/pouchdb-server/node_modules/express-pouchdb/node_modules/pouchdb-replicator/node_modules/equals/node_modules/jkroso-type/index.js:20
    if (x instanceof Map) return 'map'
                     ^
ReferenceError: Map is not defined
    at type (/usr/local/lib/node_modules/pouchdb-server/node_modules/express-pouchdb/node_modules/pouchdb-replicator/node_modules/equals/node_modules/jkroso-type/index.js:20:22)
    at equal (/usr/local/lib/node_modules/pouchdb-server/node_modules/express-pouchdb/node_modules/pouchdb-replicator/node_modules/equals/index.js:7:19)
    at onChanged (/usr/local/lib/node_modules/pouchdb-server/node_modules/express-pouchdb/node_modules/pouchdb-replicator/index.js:161:8)
    at Changes$1.<anonymous> (/usr/local/lib/node_modules/pouchdb-server/node_modules/express-pouchdb/node_modules/pouchdb-replicator/index.js:93:9)
    at Changes$1.emit (events.js:95:17)
    at Object.Changes$1.opts.onChange (/usr/local/lib/node_modules/pouchdb-server/node_modules/pouchdb/lib/index.js:710:10)
    at Changes$1.db.changes.on.on.inprogress (/usr/local/lib/node_modules/pouchdb-server/node_modules/pouchdb/lib/index.js:6056:14)
    at Changes$1.emit (events.js:95:17)
    at Object.Changes$1.opts.onChange (/usr/local/lib/node_modules/pouchdb-server/node_modules/pouchdb/lib/index.js:710:10)
    at onGetWinningDoc (/usr/local/lib/node_modules/pouchdb-server/node_modules/pouchdb/lib/index.js:7851:20)
    at onGetMetadata (/usr/local/lib/node_modules/pouchdb-server/node_modules/pouchdb/lib/index.js:7869:18)
    at /usr/local/lib/node_modules/pouchdb-server/node_modules/pouchdb/lib/index.js:7893:9
    at /usr/local/lib/node_modules/pouchdb-server/node_modules/pouchdb/node_modules/level-sublevel/shell.js:102:12
    at /usr/local/lib/node_modules/pouchdb-server/node_modules/pouchdb/node_modules/level-sublevel/nut.js:121:19
```

Trying a restart:

``` text
craig@couchdb3:~/pouchdb$ pouchdb-server -p 5985 -o 0.0.0.0
[info] pouchdb-server has started on http://0.0.0.0:5985/
[info] navigate to http://0.0.0.0:5985/_utils for the Fauxton UI.
Unhandled rejection ReferenceError: Map is not defined
    at type (/usr/local/lib/node_modules/pouchdb-server/node_modules/express-pouchdb/node_modules/pouchdb-replicator/node_modules/equals/node_modules/jkroso-type/index.js:20:22)
    at equal (/usr/local/lib/node_modules/pouchdb-server/node_modules/express-pouchdb/node_modules/pouchdb-replicator/node_modules/equals/index.js:7:19)
    at onChanged (/usr/local/lib/node_modules/pouchdb-server/node_modules/express-pouchdb/node_modules/pouchdb-replicator/index.js:161:8)
    at /usr/local/lib/node_modules/pouchdb-server/node_modules/express-pouchdb/node_modules/pouchdb-replicator/index.js:81:9
    at Array.forEach (native)
    at db.put.catch.then.then.then.db.changes.since (/usr/local/lib/node_modules/pouchdb-server/node_modules/express-pouchdb/node_modules/pouchdb-replicator/index.js:80:20)
    at Array.0 (/usr/local/lib/node_modules/pouchdb-server/node_modules/pouchdb/node_modules/lie/lib/index.js:88:21)
    at nextTick (/usr/local/lib/node_modules/pouchdb-server/node_modules/pouchdb/node_modules/lie/node_modules/immediate/lib/index.js:61:18)
    at process._tickCallback (node.js:448:13)
```

I've run under NodeJS latest (5.6.0) and back to 0.10.42, both show the same issue. 

I've written a tool that allows the user to backup databases via replication hence finding the problem, see RipcordSoftware/avancedb-replication-monitor#36. If PouchDB doesn't support local replication I'll make sure the tool disables the feature.

NB. Removing the `_replicator` directory allows `pouchdb-server` to start again.

**Comment by nolanlawson** [comment]
Cannot reproduce. This replicates documents just fine:

```bash

curl -X POST http://localhost:6984/_replicator \
  -H 'content-type:application/json' \
  -d '{"_id": "test_replication1", "source": "http://examples.cloudant.com/animaldb", "target": "animaldb", "create_target": true}'
curl -X POST http://localhost:6984/_replicator \
  -H 'content-type:application/json' \
  -d '{"_id": "test_replication2", "source": "animaldb", "target": "animaldb_2", "create_target": true}'
```
