### ISSUE TITLE
Fauxton navigation breaks when run as non-root

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb-server#183]
_From @ekoome on February 21, 2016 18:40_

I'm trying to navigate on Fauxton UI (e.g show databases, show config etc) but i get blank screen with the url redirected as follows.

Initial request:
http://localhost:3000/db/_utils/#/_all_dbs

This is redirected to be:

http://localhost:3000/db/_utils/#login?urlback=/_all_dbs

Do this have to do on authentication? Tried to click on login link but I get redirected to http://localhost:3000/db/_utils/#login?urlback=login

Here's my app:

```
var express = require ('express');
var app = express();
var PouchDB = require('pouchdb');
var riakdown = require('riakdown');

app.use('/db', require('express-pouchdb')(PouchDB));
var db = new PouchDB('acl', {db : riakdown, prefix: 'riak://localhost:8087/'});

app.listen(3000);
```

What am i missing?

_Copied from original issue: pouchdb/express-pouchdb#290_

**Comment by nolanlawson** [comment]
I think the issue here is that Fauxton is not designed to run anywhere except for the root. So the fact that you have a `/db` in there is causing it to fail.

What this issue indicates is that we should probably update Fauxton, because apparently [they fixed it recently](https://issues.apache.org/jira/browse/COUCHDB-1937) but we haven't updated since then.

**Comment by nolanlawson** [comment]
_From @deckikwok on March 27, 2016 8:13_

hmm when will this be updated(fixed)?

**Comment by nolanlawson** [comment]
_From @jure on May 13, 2016 17:26_

Hmm, I upgraded to the latest fauxton in https://github.com/jure/express-pouchdb/commits/upgrade_fauxton and I'm still getting this behaviour. I.e. navigation on Fauxton doesn't work. Sure, this is all fixable, but it's getting to a point where running a separate pouchdb-server on a different port, but using root paths for everything, is much more elegant and might be the best solution for most people (without digging into Fauxton).

**Comment by nolanlawson** [comment]
_From @jure on May 16, 2016 7:53_

Any ideas from people more familiar with Fauxton? Perhaps this navigation issue is more of a Fauxton bug, but I find it surprising that no one is having issues with express-pouchdb's Fauxton under non-root paths? Perhaps it's something else that's causing this? Or just that nobody is using Fauxton :)

**Comment by nolanlawson** [comment]
_From @DTrejo on October 5, 2016 9:17_

Here is a fix for this, it works for me. I will leave it as an exercise to the reader to clean up the code. Hope this helps!

``` js
var PORT = 3000
var DB_URL = '/db'

return main()

function main() {
  app.use(DB_URL, require('express-pouchdb')(PouchDB))
  console.log('http://localhost:%s', PORT)
  console.log()

  var mountedPouch = null
  var stack = app._router.stack
  for (var i = 0; i < stack.length; i++) {
    var route = stack[i]
    // not sure how dependable this check is.
    if (route.name === 'mounted_app' && route.regexp.test(DB_URL)) {
      mountedPouch = route
      break
    }
  }
  // console.log(mountedPouch)

  // handles requests to e.g. '/_session' '/_all_dbs' '/_users' '/_users'
  app.use(function fauxtonIntercept(req, res, next) {
    // e.g. http://localhost:3000/db/_utils/
    var referer = req.header('Referer')
    if (!referer) return next()

    var parsed = url.parse(referer)
    if (0 === parsed.pathname.indexOf(path.join(DB_URL, '/_utils/'))) {
      return mountedPouch.handle(req, res)
    }
    return next()
  })
```

**Comment by nolanlawson** [comment]
_From @bensleveritt on November 3, 2016 13:34_

I'm surprised more people don't encounter it considering this is the [first example usage of `express-pouchdb`](https://github.com/pouchdb/express-pouchdb#example-usage).

An official fix would be cool.

**Comment by nolanlawson** [comment]
_From @jwickens on December 6, 2016 23:49_

Here's my version of @DTrejo fix, thanks for this! Btw in order to officially fix this the client would need a way to discover the correct paths, which sounds more like a fauxton repo feature request than one for express-pouchdb which is probably why this has been left unsolved.  You could build a fauxton client yourself with the correct paths for your setup but that seems more work than intercepting as @DTrejo is doing. I think the docs should definitely be updated though, because it even took a while to find this issue and the fix for it as I was searching "fauxton 404 error"

```js
const express = require('express');
const app = express();
const PouchDB = require('pouchdb');
const pouchRouter = require('express-pouchdb');
const path = require('path')
const url = require('url')

const PORT = process.env.PORT || 3000;
const DB_URL = '/db';
const pouchHandle = pouchRouter(PouchDB);
const fauxtonIntercept = (req, res, next) => {
    let referer = req.header('Referer');
    if (!referer) return next();

    let parsed = url.parse(referer);
    if (0 === parsed.pathname.indexOf(path.join(DB_URL, '/_utils/'))) {
      return pouchHandle(req, res);
    }
    return next();
};

app.use(DB_URL, pouchHandle);
app.use(fauxtonIntercept);

app.listen(PORT);
console.log(`app listening on ${PORT}`);
```

**Comment by nolanlawson** [comment]
This is a bug in http://github.com/apache/couchdb-fauxton so I'm going to close for now.

**Comment by 100ideas** [comment]
I think I got [couchdb-fauxton v1.1.18](https://github.com/apache/couchdb-fauxton/commit/b8d4a30652413398e99aa8c93e77081a1a94385a) working with pouchdb.

note: `yarn link` would probably be smarter, but this is what worked for me.

note: I tried using the prepublish script in the `pouchdb-fauxton` fork but it failed in a variety of ways. so this approach just skips all that.

1. clone the couchdb-fauxton repo, defaults to folder named ``couchdb-fauxton`. `cd` into it.
2. yarn install
3. replace the `settings.json.default.json` with the source below.
4. `yarn couchdb` to build the app
5. rm -r `../<your-pouch-app>/node_modules/pouchdb-fauxton/www` to clean out busted pouchdb-fauxton
6. `cp -r dist/release/ ../<your-pouch-app>/node_modules/pouchdb-fauxton/www` - replace it with fresh package

`couchdb-fauxton/settings.json.default.json`:
```json
{
  "deps": [
  { "name": "fauxton" },
  { "name": "components" },
  { "name": "databases" },
  { "name": "documents" },
  { "name": "setup" },
  { "name": "activetasks" },
  { "name": "cluster" },
  { "name": "config" },
  { "name": "replication" },
  { "name": "cors" },
  { "name": "permissions" },
  { "name": "auth" },
  { "name": "verifyinstall" },
  { "name": "documentation" },
  { "name": "pouchdb-server" }
  ],
    "template": {
      "development": {
        "src": "./assets/index.underscore",
        "dest": "dist/debug/index.html",
        "variables": {
          "title": "Project Fauxton",
          "generationLabel": "Fauxton Dev",
          "largeLogoPath": "../../../../../assets/img/CouchDB-negative-logo.png",
          "smallLogoPath": "../../../../../assets/img/couchdb-logo.png",
          
          "bundlejs": "/bundle.js",
          "css": "./dashboard.assets/css/index.css",
          "base": null,
          "development": true
        },
        "app": {
          "root": "/",
          "host": "../..",
          "version": "1.0.dev"
        }
      },
      "release": {
        "src": "assets/index.underscore",
        "dest": "dist/release/index.html",
        "variables": {
          "title": "Project Fauxton",
          "generationLabel": "Fauxton Release",
          "largeLogoPath": "../../../../../assets/img/CouchDB-negative-logo.png",
          "smallLogoPath": "../../../../../assets/img/couchdb-logo.png",

          "bundlejs": "./dashboard.assets/js/BUNDLEJS_FILE",
          "css": "./dashboard.assets/css/CSS_FILE",
          "base": null,
          "development": false
        },
        "app": {
          "root": "/_utils",
          "host": "../..",
          "version": "1.0"
        }
      },
      "couchapp": {
        "src": "assets/index.underscore",
        "dest": "dist/debug/index.html",
        "variables": {
          "title": "Project Fauxton",
          "generationLabel": "Fauxton Pouchapp Hack",
          "largeLogoPath": "../../../../../assets/img/CouchDB-negative-logo.png",
          "smallLogoPath": "../../../../../assets/img/couchdb-logo.png",

          "bundlejs": "./js/BUNDLEJS_FILE",
          "css": "./css/CSS_FILE",
          "base": null,
          "development": false          
        },
        "app": {
          "root": "/",
          "host": "../../..",
          "version": "1.0"
        }
      }
    },

    "couch_config": {
      "fauxton": {
        "db": "http://localhost:5984/fauxton",
        "app": "./couchapp.js",
        "options": {
          "okay_if_missing": true
        }
      }
    },

    "nightwatch": {
      "fauxton_username": "tester",
      "password": "testerpass",
      "fauxton_port": "8000",
      "db_protocol": "http",
      "db_host": "localhost",
      "db_port": "5984",
      "custom_commands_path": ["test/nightwatch_tests/custom-commands", "test/nightwatch_tests/custom-commands/auth"],
      "globals_path": "test/nightwatch_tests/helpers/helpers.js",
      "selenium_port": "4444"
    }
}
```


my pouch-server `package.json`:
```json
{
  "name": "pouch",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "scripts": {
    "start": "node app.js"
  },
  "dependencies": {
    "express": "^4.16.3",
    "express-pouchdb": "^4.1.0",
    "pouchdb": "^7.0.0"
  }
}
```

**Comment by zer09** [comment]
@100ideas I am not able to build if I will change the settings

during the ```yarn couchdb``` I am getting this.

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'webpack:release' ]
2 info using npm@5.6.0
3 info using node@v8.11.4
4 verbose run-script [ 'prewebpack:release',
4 verbose run-script   'webpack:release',
4 verbose run-script   'postwebpack:release' ]
5 info lifecycle fauxton@1.1.18~prewebpack:release: fauxton@1.1.18
6 info lifecycle fauxton@1.1.18~webpack:release: fauxton@1.1.18
7 verbose lifecycle fauxton@1.1.18~webpack:release: unsafe-perm in lifecycle true
8 verbose lifecycle fauxton@1.1.18~webpack:release: PATH: /usr/lib/node_modules/npm/node_modules.bundled/npm-lifecycle/node-gyp-bin:/home/user/node/couchdb-fauxton/node_modules/.bin:/home/user/node/couchdb-fauxton/node_modules/.bin:/home/user/node/node_modules/.bin:/home/user/node_modules/.bin:/home/node_modules/.bin:/node_modules/.bin:/usr/bin:/home/user/node/couchdb-fauxton/node_modules/.bin:/home/user/.config/yarn/link/node_modules/.bin:/home/user/node/couchdb-fauxton/node_modules/.bin:/home/user/.config/yarn/link/node_modules/.bin:/usr/libexec/lib/node_modules/npm/bin/node-gyp-bin:/usr/lib/node_modules/npm/bin/node-gyp-bin:/usr/bin/node_modules/npm/bin/node-gyp-bin:/home/user/.cargo/bin:/usr/lib64/qt-3.3/bin:/usr/share/Modules/bin:/usr/lib64/ccache:/home/user/.cargo/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/home/user/.local/bin:/home/user/bin:/usr/local/go/bin:/home/user/go/bin:/opt/GitKraken:/opt/robomongo/bin:/home/user/bin:/home/user/.local/bin:/home/user/bin:/usr/local/go/bin:/home/user/go/bin:/opt/GitKraken:/opt/robomongo/bin
9 verbose lifecycle fauxton@1.1.18~webpack:release: CWD: /home/user/node/couchdb-fauxton
10 silly lifecycle fauxton@1.1.18~webpack:release: Args: [ '-c',
10 silly lifecycle   'webpack --optimize-minimize --debug --progress --colors --config ./webpack.config.release.js' ]
11 silly lifecycle fauxton@1.1.18~webpack:release: Returned: code: 2  signal: null
12 info lifecycle fauxton@1.1.18~webpack:release: Failed to exec webpack:release script
13 verbose stack Error: fauxton@1.1.18 webpack:release: `webpack --optimize-minimize --debug --progress --colors --config ./webpack.config.release.js`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules.bundled/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules.bundled/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid fauxton@1.1.18
15 verbose cwd /home/user/node/couchdb-fauxton
16 verbose Linux 4.18.8-200.fc28.x86_64
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "webpack:release"
18 verbose node v8.11.4
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 2
22 error fauxton@1.1.18 webpack:release: `webpack --optimize-minimize --debug --progress --colors --config ./webpack.config.release.js`
22 error Exit status 2
23 error Failed at the fauxton@1.1.18 webpack:release script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]

```
