### ISSUE TITLE
/dbs/<db_name>/_changes: limit parameter accepts negative values and crashes the server

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb-server#191]
_From @nolanlawson on October 27, 2016 1:35_

### Issue

When calling the _changes API, if a negative value is passed to limit parameter in query string (e.g. ?limit=-20) it will crash the server.
### Info
- Environment: Node.js 5.10.1, Chrome, Safari
- Adapter: IndexedDB, WebSQL, LevelDB
- Server based on express-pouchdb v.1.0.7
### Reproduce

Make a GET request to /dbs/<db_name>/_changes?limit=-20

Stack trace:

Application has thrown an uncaught exception and is terminated:
RangeError: Invalid array length
    at DestroyableTransform._flush (D:\home\site\wwwroot\node_modules\pouchdb\lib\index.js:4948:26)
    at DestroyableTransform.<anonymous> (D:\home\site\wwwroot\node_modules\pouchdb\node_modules\through2\node_modules\readable-stream\lib_stream_transform.js:115:49)
    at DestroyableTransform.g (events.js:273:16)
    at emitNone (events.js:80:13)
    at DestroyableTransform.emit (events.js:179:7)
    at prefinish (D:\home\site\wwwroot\node_modules\pouchdb\node_modules\through2\node_modules\readable-stream\lib_stream_writable.js:465:12)
    at finishMaybe (D:\home\site\wwwroot\node_modules\pouchdb\node_modules\through2\node_modules\readable-stream\lib_stream_writable.js:473:7)
    at endWritable (D:\home\site\wwwroot\node_modules\pouchdb\node_modules\through2\node_modules\readable-stream\lib_stream_writable.js:485:3)
    at DestroyableTransform.Writable.end (D:\home\site\wwwroot\node_modules\pouchdb\node_modules\through2\node_modules\readable-stream\lib_stream_writable.js:455:41)
    at ReadStream.onend (D:\home\site\wwwroot\node_modules\pouchdb\node_modules\readable-stream\lib_stream_readable.js:523:10)
    at ReadStream.g (events.js:273:16)
    at emitNone (events.js:80:13)
    at ReadStream.emit (events.js:179:7)
    at D:\home\site\wwwroot\node_modules\pouchdb\node_modules\readable-stream\lib_stream_readable.js:965:16
    at _combinedTickCallback (node.js:376:9)
    at process._tickCallback (node.js:407:11)

_Copied from original issue: pouchdb/express-pouchdb#394_

**Comment by nolanlawson** [comment]
Copied from https://github.com/pouchdb/pouchdb/issues/5808

**Comment by nolanlawson** [comment]
Marking this fix as easy; in `packages/node_modules/express-pouchdb/lib/routes/changes.js`, if a timeout is specified by the user, then there should be a `setTimeout()` that cancels the ongoing replication after the timeout.

The problem is that I don't believe this is easily testable, but since it's a minor change and we have a solid test suite otherwise (that actually does specify `timeout`) then I'd be confident in a PR that 1) looked good, and 2) passed the existing pouchdb tests.

**Comment by nolanlawson** [comment]
Making this fix as easy because essentially what we need to do is in `packages/node_modules/express-pouchdb/lib/routes/changes.js` we need to check the value of `limit` and if it's <1, we just clamp it to 1. (I checked, and this is what CouchDB does.)

**Comment by nolanlawson** [comment]
fixed in https://github.com/pouchdb/pouchdb-server/pull/206
