### ISSUE TITLE
pouchdb-auth: TypeError: Cannot read property 'to' of undefined

### ISSUE THREAD

**Issue by thirdhand** [pouchdb/pouchdb-server#301]
I'm still getting this error, [previously reported in the old repo](https://github.com/pouchdb/pouchdb-auth/issues/44) after upgrading to version 4.0.0:

```
    TypeError: Cannot read property 'to' of undefined
      
      at installWrappers (node_modules/pouchdb-wrappers/lib/index.js:48:29)
      at Object.<anonymous>.exports.installWrapperMethods (node_modules/pouchdb-wrappers/lib/index.js:39:3)
      at PouchDB.Object.<anonymous>.exports.installSecurityMethods (node_modules/pouchdb-security/lib/index.js:32:14)
      at Object.<anonymous>.exports.installSystemDBProtection (node_modules/pouchdb-system-db/lib/index.js:25:35)
      at node_modules/pouchdb-auth/lib/index.js:67:16
```

**Comment by thirdhand** [comment]
My bad: I used `pouchdb-adapter-memory` directly. Using `pouchdb-memory` works, probably because it includes `pouchdb-replication`.

Close if you will.

**Comment by marten-de-vries** [comment]
Ok, thanks for reporting back. I think I'll close this, if the use case for not wanting ``pouchdb-replication`` comes up we can reconsider.
