### ISSUE TITLE
Unable to start pouchdb with directory option.

### ISSUE THREAD

**Issue by chainhead** [pouchdb/pouchdb-server#327]
I have installed PouchDB on a AWS EC2 instance as shown below:

```
sudo npm install -g pouchdb-server --ignore-scripts
```

I started the server as shown below:

```
pouchdb-server -o aws-private-ip --dir /home/ubuntu/db
```

But, this is result:

```
/usr/lib/node_modules/pouchdb-server/node_modules/bindings/bindings.js:96
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /usr/lib/node_modules/pouchdb-server/node_modules/leveldown/build/leveldown.node
 → /usr/lib/node_modules/pouchdb-server/node_modules/leveldown/build/Debug/leveldown.node
 → /usr/lib/node_modules/pouchdb-server/node_modules/leveldown/build/Release/leveldown.node
 → /usr/lib/node_modules/pouchdb-server/node_modules/leveldown/out/Debug/leveldown.node
 → /usr/lib/node_modules/pouchdb-server/node_modules/leveldown/Debug/leveldown.node
 → /usr/lib/node_modules/pouchdb-server/node_modules/leveldown/out/Release/leveldown.node
 → /usr/lib/node_modules/pouchdb-server/node_modules/leveldown/Release/leveldown.node
 → /usr/lib/node_modules/pouchdb-server/node_modules/leveldown/build/default/leveldown.node
 → /usr/lib/node_modules/pouchdb-server/node_modules/leveldown/compiled/8.11.2/linux/x64/leveldown.node
    at bindings (/usr/lib/node_modules/pouchdb-server/node_modules/bindings/bindings.js:93:9)
    at Object.<anonymous> (/usr/lib/node_modules/pouchdb-server/node_modules/leveldown/leveldown.js:4:46)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/pouchdb-server/node_modules/level/level.js:1:106)
```

Can you please suggest?

**Comment by palavrohit22** [comment]
any updates here? I'm also facing same issue.
